# https://kserve.github.io/website/modelserving/v1beta1/tensorflow/
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: flower-sample
spec:
  predictor:
    tensorflow:
      # https://kserve.github.io/website/modelserving/storage/pvc/pvc/
      storageUri: "pvc://strategy-volume/saved_model"
