apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: multi-worker-training
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubeflow/multi-worker-strategy:v0.1
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /train
                  name: training
              resources:
                limits:
                  cpu: 1
          volumes:
            - name: training
              persistentVolumeClaim:
                claimName: strategy-volume
