apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tfjob-wf-
  namespace: kubeflow
spec:
  entrypoint: tfjob-wf
  templates:
  - name: tfjob-wf
    steps:
    - - name: data-ingestion-step
        template: data-ingestion-step
        arguments:
          parameters:
          - name: min
            value: 10
          - name: max
            value: 30
          - name: length
            value: 5
    - - name: distributed-tf-training-step
        template: distributed-tf-training-step
    - - name: create-model-serving-service
        template: create-model-serving-service

  - name: data-ingestion-step
    serviceAccountName: argo
    inputs:
      parameters:
      - name: min
      - name: max
      - name: length
    # TODO: User "system:serviceaccount:kubeflow:argo" cannot create resource "configmaps" in API group "" in the namespace "kubeflow"
    # memoize:
    #   key: "{{inputs.parameters.min}}-{{inputs.parameters.max}}-{{inputs.parameters.length}}"
    #   maxAge: "1h"
    #   cache:
    #     configMap:
    #       name: my-config
    #       key: step-cache
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        print(random.sample(range({{inputs.parameters.min}}, {{inputs.parameters.max}}), {{inputs.parameters.length}}))

  - name: distributed-tf-training-step
    serviceAccountName: training-operator
    resource:
      action: create
      setOwnerReference: true
      successCondition: status.replicaStatuses.Worker.succeeded = 2
      manifest: |
        apiVersion: kubeflow.org/v1
        kind: TFJob
        metadata:
          name: multi-worker-training
        spec:
          runPolicy:
            cleanPodPolicy: None
          tfReplicaSpecs:
            Worker:
              replicas: 2
              restartPolicy: Never
              template:
                spec:
                  containers:
                    - name: tensorflow
                      image: kubeflow/multi-worker-strategy:v0.1
                      imagePullPolicy: IfNotPresent
                      command: ["python", "/multi-worker-distributed-training.py", "--saved_model_dir", "/trained_model/saved_model_versions/1/", "--checkpoint_dir", "/trained_model/checkpoint"]
                      volumeMounts:
                        - mountPath: /trained_model
                          name: training
                      resources:
                        limits:
                          cpu: 500m
                  volumes:
                    - name: training
                      persistentVolumeClaim:
                        claimName: strategy-volume

  - name: create-model-serving-service
    serviceAccountName: training-operator
    successCondition: status.modelStatus.states.transitionStatus = UpToDate
    resource:
      action: create
      setOwnerReference: true
      manifest: |
        apiVersion: serving.kserve.io/v1beta1
        kind: InferenceService
        metadata:
          name: flower-sample
        spec:
          predictor:
            tensorflow:
              image: "emacski/tensorflow-serving:2.6.0"
              storageUri: "pvc://strategy-volume/saved_model_versions"